// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  v4: [{type: 'autogenerated', dirName: 'v4'}],
  user: [{type: 'autogenerated', dirName: 'user'}],
  dao: [{type: 'autogenerated', dirName: 'dao'}],
  nance: [{type: 'autogenerated', dirName: 'ecosystem/nance'}],
};

export default sidebars;
