// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  dev: [{type: 'autogenerated', dirName: 'dev'}],
  user: [{type: 'autogenerated', dirName: 'user'}],
  dao: [{type: 'autogenerated', dirName: 'dao'}],
};

export default sidebars;
