#! /bin/bash
#
# Documents a Juicebox protocol extension using `forge doc`.
# Update $JUICE_DOCS_PATH and $EXTENSIONS_PATH before running.

JUICE_DOCS_PATH="/home/f/work/juice-docs/"
EXTENSIONS_PATH="/home/f/work/juice-docs/docs/dev/extensions/"

# Check if an argument was provided
if [ -z "$1" ]; then
    echo "Usage: ./juice-doc.sh <target_path>"
    exit 1
fi

TARGET_PATH=$(realpath "$1")

# Check if Forge is installed
if ! command -v forge >/dev/null 2>&1; then
    echo "Error: Foundry (forge) was not found in your path. See https://getfoundry.sh/";
    exit 1;
fi

# Generate forge docs, store GitHub URL & forge src
cd "$TARGET_PATH"
ORIGIN=$(git remote)
ORIGIN_URL=$(git remote get-url "$ORIGIN")
FORGE_SRC=$(forge config | grep "src =" | awk -F "'" '{print $2}')
forge doc

# Make output directory, move forge docs into it, and clean up other docs files
OUTPUT_PATH="$EXTENSIONS_PATH$(basename $TARGET_PATH)"
mkdir -p "$OUTPUT_PATH"
mv docs/src/* "$OUTPUT_PATH"
rm -r docs

# Remove undesired files and autogenerated READMEs
cd "$OUTPUT_PATH"
find -type f -name README.md ! -path './README.md' -delete
rm SUMMARY.md

# Add GitHub admonition to README
awk -v admonition="\n:::info\nThis is the README from the [\`$(basename $TARGET_PATH)\`]($ORIGIN_URL) repository.\n:::\n" 'NR==1{print; print admonition; next} 1' README.md > OUTPUT.md
mv OUTPUT.md README.md

# Move files out of the forge source directory
mv $FORGE_SRC/* .
rm -r $FORGE_SRC

# Move documents out of .sol directories
for SOL in $(find ~+ -name "*.sol" -type d)
do
  mv "$SOL"/* "$SOL"/..
  rm -r $SOL
done

# Properly format documents & rename .md files: remove prefixes, make lowercase.
for FILE_PATH in $(find ~+ -name "*.md" -type f ! -name "README.md")
do
  awk 'BEGIN {prev_blank=0; prev_hash=0; prev_backticks=0} 
  {
    if ($0 ~ /^_/) {print "- " $0}
    else if ($0 ~ /^\*$/) {getline next_line; print $0 next_line}
    else if ($0 ~ /^#/) {
      if (prev_hash) {print ""}
      print $0; prev_hash=1
   }
    else if ($0 ~ /^$/) {
      if (!prev_blank) {print ""}
      prev_blank=1
    }
    else if ($0 ~ /^```$/) {
      print $0; prev_backticks=1
    }
    else {
      if (prev_backticks || prev_hash) {print ""}
      print $0
    }
    if ($0 !~ /^#/) {prev_hash=0}
    if ($0 !~ /^$/) {prev_blank=0}
    if ($0 !~ /^```$/) {prev_backticks=0}
  }' "$FILE_PATH" > "$(dirname $FILE_PATH)/$(basename $FILE_PATH | awk -F. '{ print $(NF-1) }' | tr '[:upper:]' '[:lower:]').md"
  rm "$FILE_PATH"
done

# Create Docusaurus category files and READMEs for each directory
for DIR in $(ls -d */)
do
  DIR_CLEAN=${DIR%/}
  echo -e "{\n  \"label\": \"${DIR_CLEAN^}\"\n}" > "$DIR_CLEAN"/_category_.json
	echo -e "---\ntitle: ${DIR_CLEAN^}\n---\n\nimport DocCardList from '@theme/DocCardList';\n\n<DocCardList/>" > "$DIR_CLEAN"/README.md
done
